services:
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    env_file:
      - ./backend/.env.development
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
