### Get all categories
GET http://localhost:8080/categories

### Create category
POST http://localhost:8080/categories/
Content-Type: application/json

{
  "category": "new"
}

### Update category
PATCH http://localhost:8080/categories/old
Content-Type: application/json

{
  "category": "test2"
}

### Delete category
DELETE http://localhost:8080/categories/test1/
Content-Type: application/json
