### Get all reports
GET http://localhost:8080/reports

### Get report by id
GET http://localhost:8080/reports/5

### Get reports by category
GET http://localhost:8080/reports/category/infrastructure

### Create report
POST http://localhost:8080/reports/
Content-Type: application/json

{
  "title": "title1",
  "summary": "summary1",
  "mgrs": "mgrs",
  "lat_long": "lat_long",
  "recommendations": "recommendations",
  "priority": "priority",
  "classification": "classification",
  "categories": ["infrastructure"]
}

### Update report
PATCH http://localhost:8080/reports/12
Content-Type: application/json

{
  "title": "title",
  "summary": "summary",
  "mgrs": "mgrs",
  "categories": ["infrastructure"]
}

### Delete report
DELETE http://localhost:8080/reports/6
Content-Type: application/json
