### Get all reports
GET http://localhost:8080/reports?sort_by=created_at&order=asc

### Get report
GET http://localhost:8080/reports/2

### Get reports by category
GET http://localhost:8080/reports/category/key_leader

### Create report
POST http://localhost:8080/reports/
Content-Type: application/json

{
  "title": "title1",
  "summary": "summary1",
  "mgrs": "mgrs",
  "lat_long": "lat_long",
  "recommendations": "recommendations",
  "category": "infrastructure"
}

### Update report
PATCH http://localhost:8080/reports/12
Content-Type: application/json

{
  "title": "title",
  "summary": "summary",
  "mgrs": "mgrs",
  "category": "key_leader"
}

### Delete report
DELETE http://localhost:8080/reports/2
Content-Type: application/json
