### Get all categories
GET http://localhost:8080/categories

### Create category
POST http://localhost:8080/categories/
Content-Type: application/json

{
  "category": "old"
}

### Update category
PATCH http://localhost:8080/categories/key_leader
Content-Type: application/json

{
  "category": "test"
}

### Delete category
DELETE http://localhost:8080/categories/key_leader/
Content-Type: application/json
